### ISSUE TITLE
Be coffee-script friendly

### ISSUE THREAD

**Issue by JeanSebTr** [xpensia/ImapServer#7]
- [x] stop using file's extension in require
- [x] add publish script
- [x] load coffee-script with try-catch
- [ ] consider the use of coffee-script for the whole project
- [x] but don't

**Comment by diversario** [comment]
:-1: on using CS for the entire project. Makes contributions harder.

**Comment by JeanSebTr** [comment]
As you can see, this issue is closed and all the sources are in pure javascript.

I agree with you that a project purely in CoffeeScript doesn't encourage contributions, but the goal of this commit was to prepare the ground so that someone may also make a contribution in coffee-script.

Anyway, It's great to see that someone has an interest in this project.
What's your use case for ImapServer ?

**Comment by diversario** [comment]
Well, my interest is purely academic - I like to look at projects that deal with various protocols (especially when they implement them in JS). This project popped up in my activity stream so I went to check it out and looked at issues to see if there's anything interesting that I could take a crack at.
